services:
  backend:
    build: .
    image: main-deployx-image
    container_name: main-deployx-container
    ports:
      - "4571:4571"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - ECS_CLUSTER_NAME=${ECS_CLUSTER_NAME}
      - ECS_TASK_DEFINITION=${ECS_TASK_DEFINITION}
      - ECS_CLUSTER_SUBNETS_1=${ECS_CLUSTER_SUBNETS_1}
      - ECS_CLUSTER_SUBNETS_2=${ECS_CLUSTER_SUBNETS_2}
      - ECS_CLUSTER_SUBNETS_3=${ECS_CLUSTER_SUBNETS_3}
      - ECS_CLUSTER_SECURITY_GROUP=${ECS_CLUSTER_SECURITY_GROUP}
      - DOTENV
    restart: unless-stopped
