services:
  frontend:
    build: .
    image: deployx-frontend-image
    container_name: deployx-frontend-container
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_SOCKET_URL=${VITE_SOCKET_URL}
